// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _SPA_UI_H
#define _SPA_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

  lv_obj_t *lv_example_scale_4(lv_obj_t *parent);
  lv_obj_t *scale_arc_180(lv_obj_t *parent);

  void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
